---
az_region: "westeurope"
az_resourcegroup_name: "{{ az_customer }}_{{az_purpose}}_RG"
az_purpose: "Dev"
az_customer: "test"
az_storageaccount_name: "{{ az_customer }}_{{az_purpose}}_STO"
az_storageaccount_type: "Standard_LRS"
az_storageaccount_kind: "Storage"
az_storageaccount_tier: "cool"
az_subnet_name: "{{ az_customer }}_{{az_purpose}}_Subnet"
az_virtualnet_name: "{{ az_customer }}_{{az_purpose}}_VirtNet"
az_cidr_prefix: "10.0.0.0/8"
